using STrain.Core.Enumerations;
using System.Diagnostics.CodeAnalysis;

namespace BookOfRunes.DiabloII.Resurrected.Infrastructure.Enumerations
{
    [ExcludeFromCodeCoverage]
    public class SkillEnumeration : Enumeration
    {
        public string Description { get; }
        public string Url { get; }

        public static SkillEnumeration Fanaticism => new(0, "Fanaticism", "Fanaticism increases the damage, attack speed, and attack rating of the Paladin and everyone in his party.", "https://diablo2.wiki.fextralife.com/Fanaticism");
        public static SkillEnumeration Werebear => new(1, "Werebear", "This skill enables the Druid to transform into a Werebear. It includes substantial bonuses to his defense, damage, and life.", "https://diablo2.wiki.fextralife.com/Werebear");
        public static SkillEnumeration Lycanthropy => new(2, "Lycanthropy", "This skill adds a passive bonus that allows the Druid to remain in fur form much longer. There is also a substantial hit point boost.", "https://diablo2.wiki.fextralife.com/Lycanthropy");
        public static SkillEnumeration SummonGrizzly => new(3, "Summon Grizzly", "Summoned Grizzlies are fierce minions, capable of inflicting heavy damage. Grizzlies move slowly, but have strong attacks that stun and knock back their targets.", "https://diablo2.wiki.fextralife.com/Summon+Grizzly");
        public static SkillEnumeration CorpseExplosion => new(4, "Corpse Explosion", "One of the messiest and most fun skills in the game, Corpse Explosion detonates fallen monster corpses in messy sprays of bone and blood, striking all nearby enemies for substantial fire and physical damage.", "https://diablo2.wiki.fextralife.com/Corpse+Explosion");
        public static SkillEnumeration BoneArmor => new(5, "Bone Armor", "An orbiting shield that absorbs a set amount of physical damage before vanishing.", "https://diablo2.wiki.fextralife.com/Bone_Armor");
        public static SkillEnumeration BoneSpear => new(6, "Bone Spear", "Bone Spear fires a straight shot of magical damage bone that can pass through any number of targets. It does less damage to each target than Bone Spirit (until very high levels), but can hit multiple enemies, and is very effective against large mobs, or in narrow hallways, such as inside the Maggot Lair. Their damage is magical so only by raise skill levels can you increase it.", "https://diablo2.wiki.fextralife.com/Bone_Spear");
        public static SkillEnumeration Thorns => new(7, "Thorns", "Creates a spiky barrier around the Paladin and all in his party, reflecting huge damage back against melee, physical attackers. Has no effect against ranged or elemental attacks.", "https://diablo2.wiki.fextralife.com/Thorns");
        public static SkillEnumeration SpiritOfBarbs => new(8, "Spirit of Barbs", "This spirit bestows a Thorns aura on the Druid and all in his party.", "https://diablo2.wiki.fextralife.com/Spirit+of+Barbs");
        public static SkillEnumeration AmplifyDamage => new(9, "Amplify Damage", "Amplify damage greatly increases the physical damage taken by any afflicted target.", "https://diablo2.wiki.fextralife.com/Amplify+Damage");
        public static SkillEnumeration ExplodingArrow => new(10, "Exploding Arrow", "Enchants arrows by adding explosive fire damage to them. The flame splashes enough to strike several monsters in a tight cluster, and there is an accuracy bonus as well.", "https://diablo2.wiki.fextralife.com/Exploding+Arrow");
        public static SkillEnumeration PoisonNova => new(11, "Poison Nova", "Poison Nova sends out an expanding circle of toxic bolts, poisoning everything within range, and virtually everything on the screen.", "https://diablo2.wiki.fextralife.com/Poison+Nova");
        public static SkillEnumeration BattleCommand => new(12, "Battle Command", "Battle Command adds a +1 to all of the Barbarian's skills, and does the same for all characters and minions in his party.", "https://diablo2.wiki.fextralife.com/Battle+Command");
        public static SkillEnumeration BattleOrder => new(13, "Battle Orders", "Improve party members' life, mana and stamina.", "https://diablo2.wiki.fextralife.com/Battle+Orders");
        public static SkillEnumeration BattleCry => new(14, "Battle Cry", "Fearsome cry reduces enemy effectiveness.", "https://diablo2.wiki.fextralife.com/Battle+Cry");
        public static SkillEnumeration FrozenOrb => new(15, "Frozen Orb", "One of the more awesome spells in the game, Frozen Orb fires out a glowing orb of ice that spins across most of the visible screen, emitting dozens of tiny Ice Bolts in all directions.", "https://diablo2.wiki.fextralife.com/Frozen+Orb");
        public static SkillEnumeration ChargedBolt => new(16, "Charged Bolt", "Charged bolt is one of the first skills a sorceress can learn, and is one of the few level 1 skills that scales well end game.", "https://diablo2.wiki.fextralife.com/Charged+Bolt");
        public static SkillEnumeration Whirlwind => new(17, "Whirlwind", "Whirlwind is the Tasmanian Devil of Barbarian skills, turning the character into a spinning death-dealer, capable of passing through huge mobs and hitting dozens of targets with a single use of the skill.", "https://diablo2.wiki.fextralife.com/Whirlwind");
        public static SkillEnumeration ChainLightning => new(18, "Chain Lightning", "Chain Lightning jumps from target to target, and can be quite impressive when cast on a cluster of enemies.", "https://diablo2.wiki.fextralife.com/Chain+Lightning");
        public static SkillEnumeration StaticField => new(19, "Static Field", "Static Field hits every monster in range, instantly chopping 25% off of their current hit points (similar to crushing blow).", "https://diablo2.wiki.fextralife.com/Static");
        public static SkillEnumeration SummonSpiritWolf => new(20, "Summon Spirit Wolf", "This gift of Nature allows the Druid to conjure forth one or more wolf allies who, with their mystical powers, provide the Druid a potent and ferocious colleague.", "https://diablo2.wiki.fextralife.com/Summon+Spirit+Wolf");
        public static SkillEnumeration GlacialSpike => new(21, "Glacial Spike", "Shoots a large snowball that hits with substantial damage and a large splash effect, freezing the targeted monster and anything within 2.6 yards.", "https://diablo2.wiki.fextralife.com/Glacial+Spike");
        public static SkillEnumeration BloodGolem => new(22, "Blood Golem", "Blood Golems are linked to the Necromancer who casts them. As the Blood Golem damages the target it leeches life, and shares this with the Necromancer.", "https://diablo2.wiki.fextralife.com/Blood+Golem");
        public static SkillEnumeration MindBlast => new(23, "Mind Blast", "Focusing her anima, an Assassin using this potent ability can crush the will of a group of enemies. Mind Blast stuns and confuses the feeble minded into attacking their comrades.", "https://diablo2.wiki.fextralife.com/Mind+Blast");
        public static SkillEnumeration Terror => new(24, "Terror", "Cursed monsters run away at very high speed.", "https://diablo2.wiki.fextralife.com/Terror");
        public static SkillEnumeration Confuse => new(25, "Confuse", "Confused monsters attack whatever target is nearest them, including other monsters.", "https://diablo2.wiki.fextralife.com/Confuse");
        public static SkillEnumeration Volcano => new(26, "Volcano", "A more powerful version of Fissure, the Volcano erupts from one point and deals substantial fire damage to everything in the vicinity.", "https://diablo2.wiki.fextralife.com/Volcano");
        public static SkillEnumeration HolyFreeze => new(27, "Holy Freeze", "This aura chills and slows the movement and attack speed of all enemies within range. It also deals constant cold damage, and adds cold damage to the Paladin's attacks.", "https://diablo2.wiki.fextralife.com/Holy+Freeze");
        public static SkillEnumeration Venom => new(28, "Venom", "Poison use is another technique an Assassin has to help even the odds when battling demons and their ilk. An Assassin who has mastered this skill secretly coats her weapons with vile toxins.", "https://diablo2.wiki.fextralife.com/Venom");
        public static SkillEnumeration Hydra => new(29, "Hydra", "Hydras are three-headed dragons composed of pure flame. The heads each fire a constant stream of Fire Bolts, dealing damage to the target, but not splashing to the sides.", "https://diablo2.wiki.fextralife.com/Hydra");
        public static SkillEnumeration HolyFire => new(30, "Holy Fire", "Holy Fire adds fire damage to the Paladin's attacks, as well as dealing a few points of fire damage to every monster in range.", "https://diablo2.wiki.fextralife.com/Holy+Fire");
        public static SkillEnumeration HolyShock => new(31, "Holy Shock", "Holy Shock adds lightning damage to the Paladin's attacks, as well as dealing a few points of lightning damage to every monster in range.", "https://diablo2.wiki.fextralife.com/Holy+Shock");
        public static SkillEnumeration Teleport => new(32, "Teleport", "Teleport moves the Sorceress instantly to any valid location she can point her cursor at.", "https://diablo2.wiki.fextralife.com/Teleport");
        public static SkillEnumeration Blaze => new(33, "Blaze", "Blaze leaves a trail of fire behind the Sorceress as she walks or runs along, for as long as she keeps the spell active.", "https://diablo2.wiki.fextralife.com/Blaze");
        public static SkillEnumeration Fireball => new(34, "Fireball", "A substantial upgrade from Firebolt, Fireballs are larger and more damaging, and they hit with splash damage, burning the target and any nearby monsters too.", "https://diablo2.wiki.fextralife.com/Fireball");
        public static SkillEnumeration Warmth => new(35, "Warmth", "Warmth increases the Sorceress' mana regeneration rate.", "https://diablo2.wiki.fextralife.com/Warmth");
        public static SkillEnumeration Revive => new(36, "Revive", "Revives the dead monster, raising it up in its living form, but coloured dark gray.", "https://diablo2.wiki.fextralife.com/Revive");
        public static SkillEnumeration LifeTap => new(37, "Life Tap", "Life Tap causes huge life leech to flow to any physical damage attacker.", "https://diablo2.wiki.fextralife.com/Life+Tap");
        public static SkillEnumeration Defiance => new(38, "Defiance", "This aura boosts the defense of the Paladin and all characters and minions in his party.", "https://diablo2.wiki.fextralife.com/Defiance");
        public static SkillEnumeration ChillingArmor => new(39, "Chilling Armor", "Chilling Armor provides a slightly smaller defensive bonus than Shiver Armor (but larger than Frozen Armor).", "https://diablo2.wiki.fextralife.com/Chilling+Armor");
        public static SkillEnumeration Frenzy => new(40, "Frenzy", "Frenzy allows the Barbarian to strike and move much faster, with any skill.", "https://diablo2.wiki.fextralife.com/Frenzy");
        public static SkillEnumeration DimVision => new(41, "Dim Vision", "Monsters that have had their vision dimmed no longer see their enemies.", "https://diablo2.wiki.fextralife.com/Dim+Vision");
        public static SkillEnumeration Meteor => new(42, "Meteor", "A flaming ball of rock is called down from above, dealing explosive damage to the target and leaving a patch of fiery burning earth behind.", "https://diablo2.wiki.fextralife.com/Meteor");
        public static SkillEnumeration Vigor => new(43, "Vigor", "Vigor boosts the running speed, maximum stamina, and stamina regeneration rate for the Paladin and all in his party.", "https://diablo2.wiki.fextralife.com/Vigor");
        public static SkillEnumeration Valkyrie => new(44, "Valkyrie", "Valkyries are powerful magical tanks. They spawn with high defense and hit points, and can stand up to a tremendous amount of damage.", "https://diablo2.wiki.fextralife.com/Valkyrie");
        public static SkillEnumeration OakSage => new(45, "Oak Sage", "The Oak Sage spirit floats around, radiating a hit point enhancing aura that affects the Druid and all characters and minions in his party.", "https://diablo2.wiki.fextralife.com/Oak+Sage");
        public static SkillEnumeration Raven => new(46, "Raven", "Ravens swarm in a cloud and look nifty, but their damage is negligible and their AI is lacking.", "https://diablo2.wiki.fextralife.com/Raven");
        public static SkillEnumeration Blizzard => new(47, "Blizzard", "Blizzard is an area effect spell, calling down an icy storm that chills and cold damages everything over a wide area.", "https://diablo2.wiki.fextralife.com/Blizzard");
        public static SkillEnumeration FrostNova => new(48, "Frost Nova", "Creates and expanding ring of ice that damages enemies with cold damage and slows enemies.", "https://diablo2.wiki.fextralife.com/Frost+Nova");
        public static SkillEnumeration Conviction => new(49, "Conviction", "This aura lowers the defense and fire, lightning, and cold resistances of monsters, making it ideal to pair with an elemental weapon or skill, such as Vengeance.", "https://diablo2.wiki.fextralife.com/Conviction");
        public static SkillEnumeration CycloneArmor => new(50, "Cyclone Armor", "This shielding spell is essentially an elemental version of the Necromancer's Bone Shield. It absorbs a set amount of elemental damage, but has no effect against physical attacks.", "https://diablo2.wiki.fextralife.com/Cyclone+Armor");
        public static SkillEnumeration Meditation => new(51, "Meditation", "Boosts the mana regeneration rate for the Paladin and all his party members.", "https://diablo2.wiki.fextralife.com/Meditation");
        public static SkillEnumeration Twister => new(52, "Twister", "Each cast of Twister sets up a small tornado that stuns and deals physical damage to any enemies in the area.", "https://diablo2.wiki.fextralife.com/Twister");
        public static SkillEnumeration Vengeance => new(53, "Vengeance", "A powerful single-hit attack that adds fire, lightning, and cold damage.", "https://diablo2.wiki.fextralife.com/Vengeance");
        public static SkillEnumeration Fade => new(54, "Fade", "Raises all resistances and resists curses for a period of time.", "https://diablo2.wiki.fextralife.com/Fade");
        public static SkillEnumeration Might => new(55, "Might", "Might increases the output of all physical damage attacks by the Paladin or his party.", "https://diablo2.wiki.fextralife.com/Might");
        public static SkillEnumeration Decrepify => new(56, "Decrepify", "This powerful curse lowers movement, attack speed, damage and physical resistance by 50%.", "https://diablo2.wiki.fextralife.com/Decrepify");
        public static SkillEnumeration Sanctuary => new(57, "Sanctuary", "This aura only works against the Undead, but provides the Paladin with a substantial damage bonus, as well as working to push back and constantly deal holy damage to all Undead in range.", "https://diablo2.wiki.fextralife.com/Sanctuary");
        public static SkillEnumeration Inferno => new(58, "Inferno", "Inferno turns a Sorceress into a human flamethrower, capable of emitting a massive spout of flame for as long as the spell is kept active.", "https://diablo2.wiki.fextralife.com/Inferno");
        public static SkillEnumeration FireBolt => new(59, "Fire Bolt", "Shoots a small ball of fire. Fire Bolts hit only one target and have no splash damage.", "https://diablo2.wiki.fextralife.com/Fire+Bolt");
        public static SkillEnumeration SlowMissiles => new(60, "Slow Missiles", "A curse-like debuff skill that slows the missles of all monsters within the skill's range.", "https://diablo2.wiki.fextralife.com/Slow_Missiles");
        public static SkillEnumeration Dodge => new(61, "Dodge", "Allows the Amazon to dodge melee attacks while standing still or attacking.", "https://diablo2.wiki.fextralife.com/Dodge");
        public static SkillEnumeration CriticalStrike => new(62, "Critical Strike", "This extremely powerful skill gives a chance to deal a critical strike, doubling the physical damage of an attack with any sort of weapon.", "https://diablo2.wiki.fextralife.com/Critical+Strike");
        public static SkillEnumeration EnergyShield => new(63, "Energy Shield", "Energy Shield allows the Sorceress to redirect damage from life to mana.", "https://diablo2.wiki.fextralife.com/Energy+Shield");
        public static SkillEnumeration Howl => new(64, "Howl", "Howling will cause affected monsters to cease attacking and retreat as a green 'rain' drizzles down on them.", "https://diablo2.wiki.fextralife.com/Howl");
        public static SkillEnumeration Taunt => new(65, "Taunt", "Taunt is set up to get those pesky fleeing monsters to come to you.", "https://diablo2.wiki.fextralife.com/Taunt");
        public static SkillEnumeration CloackOfShadows => new(66, "Cloak of Shadows", "This spell blocks some monster effects; sand maggots cannot lay eggs, unravelers cannot use their poison breath, venom lords cannot use their Inferno attack etc.", "https://diablo2.wiki.fextralife.com/Cloak+of+Shadows");
        public static SkillEnumeration BoneSpirit => new(67, "Bone Spirit", "Bone Spirits are slow-moving, homing missiles that will track targets for quite a distance off the screen.", "https://diablo2.wiki.fextralife.com/Bone+Spirit");
        public static SkillEnumeration HeartOfWolverine => new(68, "Heart of Wolverine", "This spirit's aura provides a hearty attack rating and damage bonus to the Druid and all players and minions in his party.", "https://diablo2.wiki.fextralife.com/Heart+of+Wolverine");
        public static SkillEnumeration IronGolem => new(69, "Iron Golem", "This golem is created from the item, and takes on properties of the item.", "https://diablo2.wiki.fextralife.com/Iron+Golem");
        public static SkillEnumeration Enchant => new(70, "Enchant", "Temporarily grants bonus fire damage and boosts the Attack Rating of any friendly player or minion.", "https://diablo2.wiki.fextralife.com/Enchant");
        public static SkillEnumeration Berserk => new(71, "Berserk", "Berserk gives the Barbarian a way to deal a huge amount of magical (non-physical) damage with a melee attack, saving him from needing to use elemental damage weapons to kill Stone Skin and Physical Immune monsters.", "https://diablo2.wiki.fextralife.com/Berserk");
        public static SkillEnumeration Zeal => new(72, "Zeal", "Zeal is a rapid, multi-strike attack with substantial bonuses to attack rating, attack speed, and damage.", "https://diablo2.wiki.fextralife.com/Zeal");
        public static SkillEnumeration Firestorm => new(73, "Firestorm", "Wielding this ability, the Druid projects waves of molten earth that spread outward and burn a wide swath of destruction through his foes.", "https://diablo2.wiki.fextralife.com/Firestorm");
        public static SkillEnumeration Redemption => new(74, "Redemption", "Redemption uses up corpses, making them vanish with a lovely rising spirit graphic (also seen coming up from the skeletons after Radament is defeated in the Act Two Sewers), and transferring substantial mana and life to the Paladin.", "https://diablo2.wiki.fextralife.com/Redemption");
        public static SkillEnumeration FireWall => new(75, "Fire Wall", "A wall of flame springs up in both directions from the spot the Sorceress targets for ignition.", "https://diablo2.wiki.fextralife.com/Fire+Wall");
        public static SkillEnumeration Concentration => new(76, "Concentration", "Concentration greatly increases the physical damage of the Paladin and all in his party.", "https://diablo2.wiki.fextralife.com/Concentration");
        public static SkillEnumeration HolyBolt => new(77, "Holy Bolt", "A glowing, magical projectile is fired out at a medium rate of speed.", "https://diablo2.wiki.fextralife.com/Holy+Bolt");
        public static SkillEnumeration Tornado => new(78, "Tornado", "An upgraded version of Twister, a Tornado is much larger and more powerful, but lacks the stunning effect of the smaller Twisters.", "https://diablo2.wiki.fextralife.com/Tornado");
        public static SkillEnumeration IronMaiden => new(79, "Iron Maiden", "Causes the physical, melee damage inflicted by the target to reflect back to themselves.", "https://diablo2.wiki.fextralife.com/Iron+Maiden");
        public static SkillEnumeration Weaken => new(80, "Weaken", "Lowers the physical damage the target inflicts by 33%.", "https://diablo2.wiki.fextralife.com/Weaken");
        public static SkillEnumeration MoltenBoulder => new(81, "Molten Boulder", "A fun skill to use, this one sends forth a rolling boulder of molten stone.", "https://diablo2.wiki.fextralife.com/Molten+Boulder");
        public static SkillEnumeration ClayGolem => new(82, "Clay Golem", "Raises a Golem from the earth to fight for you.", "https://diablo2.wiki.fextralife.com/Clay+Golem");
        public static SkillEnumeration PosionExplosion => new(83, "Poison Explosion", "Like Corpse Explosion, but with poison damage.", "https://diablo2.wiki.fextralife.com/Poison+Explosion");
        public static SkillEnumeration IceBlast => new(84, "Ice Blast", "Shoots a large snowball that hits with cold damage, freezing the target.", "https://diablo2.wiki.fextralife.com/Ice+Blast");
        public static SkillEnumeration SkeletonMastery => new(85, "Skeleton Mastery", "Increases the hit points and damage dealt by Skeletons, Skeleton Mages, and Revived.", "https://diablo2.wiki.fextralife.com/Skeleton+Mastery");
        public static SkillEnumeration Attract => new(86, "Attract", "A monster with Attract cast on it becomes the target of aggression to all other monsters in the vicinity.", "https://diablo2.wiki.fextralife.com/Attract");
        public static SkillEnumeration Nova => new(87, "Nova", "Nova casts an expanding ring of lightning that strikes everything in its path, extending nearly to the edge of the screen.", "https://diablo2.wiki.fextralife.com/Nova");
        public static SkillEnumeration LowerResist => new(88, "LowerResist", "Curses an enemy to take more damage from all magical attack lowers resistances of monsters lowers maximum resistances of hostile players. ", "https://diablo2.wiki.fextralife.com/Lower+Resist");
        public static SkillEnumeration Cleansing => new(89, "Cleansing", "Reduces Poison and Curse duration for all party members.", "https://diablo2.wiki.fextralife.com/Cleansing");
        public static SkillEnumeration ResistFire => new(90, "Resist Fire", "Increases the Fire resistance of all party members.", "https://diablo2.wiki.fextralife.com/Resist+Fire");

        public SkillEnumeration(int id, string name, string description, string url)
            : base(id, name)
        {
            Description = description;
            Url = url;
        }
    }
}
