// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BookOfRunes.DiabloII.Resurrected.Test.E2E.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CM_CharacterManagementFeature : object, Xunit.IClassFixture<CM_CharacterManagementFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "CM - Character Management", ("Allows to manage characters with names and levels. Character can be added, levele" +
                "d up or deleted."), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CharacterManagement.feature"
#line hidden
        
        public CM_CharacterManagementFeature(CM_CharacterManagementFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[E2E][CM/AC-001]: Add first character")]
        [Xunit.TraitAttribute("FeatureTitle", "CM - Character Management")]
        [Xunit.TraitAttribute("Description", "[E2E][CM/AC-001]: Add first character")]
        [Xunit.TraitAttribute("Category", "e2e")]
        public async System.Threading.Tasks.Task E2ECMAC_001AddFirstCharacter()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[E2E][CM/AC-001]: Add first character", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await testRunner.WhenAsync("Opening the application", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
  await testRunner.ThenAsync("Character creator should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[E2E][CM/AC-002]: Add Character")]
        [Xunit.TraitAttribute("FeatureTitle", "CM - Character Management")]
        [Xunit.TraitAttribute("Description", "[E2E][CM/AC-002]: Add Character")]
        [Xunit.TraitAttribute("Category", "e2e")]
        public async System.Threading.Tasks.Task E2ECMAC_002AddCharacter()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[E2E][CM/AC-002]: Add Character", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
  await testRunner.GivenAsync("\'Harding\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
  await testRunner.WhenAsync("Adding \'Logen\' character", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
  await testRunner.ThenAsync("\'Logen\' should be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[E2E][CM/LU-001]: Level up characater")]
        [Xunit.TraitAttribute("FeatureTitle", "CM - Character Management")]
        [Xunit.TraitAttribute("Description", "[E2E][CM/LU-001]: Level up characater")]
        [Xunit.TraitAttribute("Category", "e2e")]
        public async System.Threading.Tasks.Task E2ECMLU_001LevelUpCharacater()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[E2E][CM/LU-001]: Level up characater", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
  await testRunner.GivenAsync("\'Harding\' character is added with level 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
  await testRunner.WhenAsync("Leveling up \'Harding\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
  await testRunner.ThenAsync("Level should be 19", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[E2E][CM/DC-001]: Delete character")]
        [Xunit.TraitAttribute("FeatureTitle", "CM - Character Management")]
        [Xunit.TraitAttribute("Description", "[E2E][CM/DC-001]: Delete character")]
        [Xunit.TraitAttribute("Category", "e2e")]
        public async System.Threading.Tasks.Task E2ECMDC_001DeleteCharacter()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[E2E][CM/DC-001]: Delete character", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
  await testRunner.GivenAsync("\'Harding\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
  await testRunner.AndAsync("\'Logen\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
  await testRunner.WhenAsync("Deleting \'Harding\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
  await testRunner.ThenAsync("\'Logen\' should be selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[E2E][CM/DC-002]: Delete last character")]
        [Xunit.TraitAttribute("FeatureTitle", "CM - Character Management")]
        [Xunit.TraitAttribute("Description", "[E2E][CM/DC-002]: Delete last character")]
        [Xunit.TraitAttribute("Category", "e2e")]
        public async System.Threading.Tasks.Task E2ECMDC_002DeleteLastCharacter()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[E2E][CM/DC-002]: Delete last character", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
  await testRunner.GivenAsync("\'Harding\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
  await testRunner.WhenAsync("Deleting \'Harding\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
  await testRunner.ThenAsync("Character creator should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[E2E][CM/SC-001]: Select next character")]
        [Xunit.TraitAttribute("FeatureTitle", "CM - Character Management")]
        [Xunit.TraitAttribute("Description", "[E2E][CM/SC-001]: Select next character")]
        [Xunit.TraitAttribute("Category", "e2e")]
        public async System.Threading.Tasks.Task E2ECMSC_001SelectNextCharacter()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[E2E][CM/SC-001]: Select next character", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
  await testRunner.GivenAsync("\'Harding\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
  await testRunner.AndAsync("\'Logen\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
  await testRunner.AndAsync("\'Harding\' is selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
  await testRunner.WhenAsync("Selecting next character", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
  await testRunner.ThenAsync("\'Logen\' should be selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[E2E][CM/SC-002]: Select previous character")]
        [Xunit.TraitAttribute("FeatureTitle", "CM - Character Management")]
        [Xunit.TraitAttribute("Description", "[E2E][CM/SC-002]: Select previous character")]
        [Xunit.TraitAttribute("Category", "e2e")]
        public async System.Threading.Tasks.Task E2ECMSC_002SelectPreviousCharacter()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[E2E][CM/SC-002]: Select previous character", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
  await testRunner.GivenAsync("\'Harding\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
  await testRunner.AndAsync("\'Logen\' character is added", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
  await testRunner.AndAsync("\'Logen\' is selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
  await testRunner.WhenAsync("Selecting previous character", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
  await testRunner.ThenAsync("\'Harding\' should be selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CM_CharacterManagementFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CM_CharacterManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
