name: CD Pipeline
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  get-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute
        id: version
        uses: mihben/actions-repository/.github/actions/get-version@main

  publish-backend:
    needs: [get-version]
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute
        uses: mihben/actions-repository/.github/actions/dotnet/publish/webapi@main
        with:
          working-directory: src/BookOfRunes.DiabloII.Resurrected
          project: BookOfRunes.DiabloII.Resurrected
          token: ${{ secrets.GITHUB_TOKEN }}
          target_image: bookofrunes/diablo2/resurrected/backend
          target_version: ${{ needs.get-version.outputs.version }}

  publish-client:
    needs: [get-version]
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute
        uses: mihben/actions-repository/.github/actions/dotnet/publish/wasm@main
        with:
          working-directory: src/BookOfRunes.DiabloII.Resurrected.WASM
          project: BookOfRunes.DiabloII.Resurrected.WASM
          token: ${{ secrets.GITHUB_TOKEN }}
          target_image: bookofrunes/diablo2/resurrected/client
          target_version: ${{ needs.get-version.outputs.version }}
