name: CD Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Get Version
        id: version
        run: echo "TARGET_VERSION=${{ github.ref_name }} | cut -c 2-" >> $GITHUB_OUTPUT

      - name: Publish
        run: dotnet publish src/RuneDex.DiabloII.Resurrected/RuneDex.DiabloII.Resurrected.csproj --configuration Release --output artifacts/backend/

      - name: Create Docker Image
        run: |
          wget https://raw.githubusercontent.com/mihben/actions-repository/refs/heads/feature/dotnet-publish/dockerfiles/dotnet/webapi/Dockerfile
          sed -i 's/#WEBAPI_DLL#/RuneDex.DiabloII.Resurrected.dll/g' *
          cat Dockerfile
        working-directory: artifacts/backend/
