name: "Pull Request Title"

on: workflow_dispatch

jobs:
  restore-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Dependencies
        uses: mihben/actions-repository/.github/actions/dotnet/restore-dependencies@feature/dotnet-actions
        with:
          working-directory: src
          packages-directory: ./nuget-packages
