name: E2E Test Pipeline
run-name: 'E2E Test ${{ github.ref_name }}'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_browser: ['chromium', 'firefox', 'webkit']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute (${{ matrix.target_browser }})
        uses: mihben/actions-repository/.github/actions/dotnet/e2e-test@feature/run-e2e-tests
        with:
          target_browser: ${{ matrix.target_browser }}
          url: https://bookofrunes.mihben.site/
          working_directory: specs
