name: release
run-name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute
        uses: mihben/actions-repository/.github/actions/dotnet/release@feature/dotnet-publish
